from database.model.produto import Produto

produtos = [ Produto ( id_produtos ='picanha'
                     , nome = 'Picanha'
                     , fornecedor = 'Frigorífico Argentino'
                     , preco =  30.30
                     , categoria = 'Carnes'
                     , informacao = 'Quantidade: 150 G'
                     , detalhamento = 'Na nossa busca incessante pela perfeição gastronômica, apresentamos a Picanha Suprema: um verdadeiro tesouro de sabor e maciez. Cuidadosamente selecionada a partir das melhores raças de gado, nossa picanha é uma sinfonia de suculência e textura que transcende todas as expectativas. Proveniente da parte traseira do boi, próxima à cauda, esse corte triangular é um presente para os amantes de churrasco e apreciadores da alta gastronomia. Com seu marmoreio perfeito e a camada de gordura que se derrete durante o cozimento, a Picanha Suprema proporciona uma experiência sensorial única, onde cada mordida revela um sabor intenso e suculento.'
                     , destaques = 'S' )
           , Produto ( id_produtos ='alcatra'
                     , nome = 'Alcatra'
                     , fornecedor = 'Frigorífico Brasileiro'
                     , preco =  20.10
                     , categoria = 'Carnes'
                     , informacao = 'Quantidade: 130 G'
                     , detalhamento = 'Em nossa incessante busca por excelência gastronômica, temos o prazer de apresentar a Alcatra Nobre: uma verdadeira joia de sabor e tenacidade. Rigorosamente escolhida dentre as melhores raças bovinas, nossa alcatra é uma harmonia de suculência e textura que surpreende todas as expectativas. Proveniente da parte traseira do boi, próxima ao quadril, essa peça de carne é um deleite para os paladares mais exigentes, oferecendo uma experiência gastronômica única e irresistível. Com marmoreio equilibrado, a Alcatra Nobre é o resultado de um cuidadoso processo de seleção, garantindo uma carne tenra e repleta de sabor que certamente satisfará os apreciadores de uma refeição requintada.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='fraldinha'
                     , nome = 'Fraldinha'
                     , fornecedor = 'Frigorífico Mineiro'
                     , preco =  18.45
                     , categoria = 'Carnes'
                     , informacao = 'Quantidade: 140 G'
                     , detalhamento = 'Em nossa busca incansável pela excelência culinária, temos o prazer de apresentar a Fraldinha Especial: um verdadeiro tesouro de sabor e suculência. Selecionada cuidadosamente entre as melhores carnes bovinas, nossa fraldinha é uma sinfonia de textura macia e sabor único que surpreenderá todas as suas expectativas. Proveniente da região abdominal do boi, conhecida como fralda, esse corte é uma delícia para os paladares mais exigentes, proporcionando uma experiência gastronômica excepcional e irresistível.'
                     , destaques = 'N' ) 
           , Produto ( id_produtos ='cupim'
                     , nome = 'Cupim'
                     , fornecedor = 'Frigorífico Mineiro'
                     , preco =  20.30
                     , categoria = 'Carnes'
                     , informacao = 'Quantidade: 150 G'
                     , detalhamento = 'Com sua textura suculenta e sabor distintivo, o cupim oferece uma experiência gastronômica única. Selecionado com cuidado, esse corte apresenta uma combinação equilibrada de marmoreio e gordura, proporcionando um sabor rico e uma maciez excepcional. Com sua localização privilegiada, o cupim é perfeito para ser assado lentamente, resultando em uma carne macia e suculenta, cheia de aromas e sabores intensos. Delicie-se com o cupim e descubra o prazer de saborear um corte de carne bovina de qualidade, proveniente de uma região especial do animal.'
                     , destaques = 'S' )           
           , Produto ( id_produtos ='picanhasuina'
                     , nome = 'Picanha Suína'
                     , fornecedor = 'Frigorífico Goiano'
                     , preco =  14.70
                     , categoria = 'Carnes'
                     , informacao = 'Quantidade: 100 G'
                     , detalhamento = 'Com sua textura suculenta e sabor marcante, a picanha suína é uma verdadeira delícia para os apreciadores da carne de porco. Selecionada cuidadosamente, essa carne oferece uma experiência gastronômica única e irresistível. Com seu marmoreio equilibrado e uma camada de gordura que traz suculência e sabor durante o preparo, a picanha suína apresenta um sabor rico e uma maciez inigualável. Permita-se desfrutar dessa iguaria que combina tradição, qualidade e prazer em cada mordida, elevando sua refeição a um patamar excepcional.'
                     , destaques = 'N' )                         
           , Produto ( id_produtos ='maminha'
                     , nome = 'Maminha'
                     , fornecedor = 'Frigorífico Gaúcho'
                     , preco =  15.75
                     , categoria = 'Carnes'
                     , informacao = 'Quantidade: 100 G'
                     , detalhamento = 'Com sua textura macia e sabor suculento, a maminha é um verdadeiro deleite para os apreciadores de carne. Selecionada criteriosamente, essa peça proporciona uma experiência gastronômica única e encantadora. Com seu equilíbrio perfeito entre marmoreio e magreza, a maminha oferece um sabor rico e uma textura tenra que a tornam ideal para grelhados, assados ou até mesmo para ser fatiada em bifes suculentos. Permita-se desfrutar dessa iguaria que combina qualidade, suculência e sabor, elevando sua refeição a outro nível de prazer culinário.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='frango'
                     , nome = 'Asinha de Frango'
                     , fornecedor = 'Frigorífico Brasileiro'
                     , preco =  8.15
                     , categoria = 'Carnes'
                     , informacao = 'Quantidade: 100 G'
                     , detalhamento = 'Com sua textura tenra e sabor irresistível, as asinhas de frango são um verdadeiro prazer para os amantes de carne. Selecionadas com cuidado, essas porções proporcionam uma experiência gastronômica única e deliciosa. Com seu equilíbrio perfeito entre carne e osso, as asinhas de frango são ideais para serem temperadas, marinadas e assadas, resultando em pedaços suculentos e crocantes. A versatilidade das asinhas de frango permite que sejam preparadas de diversas formas, como grelhadas, fritas, empanadas ou até mesmo cozidas em molhos saborosos. Seja como aperitivo em festas ou como prato principal, as asinhas de frango são sempre uma escolha deliciosa e apreciada por pessoas de todas as idades.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='linguica'
                     , nome = 'Linguiça Suína'
                     , fornecedor = 'Frigorífico Brasileiro'
                     , preco =  10.05
                     , categoria = 'Carnes'
                     , informacao = 'Quantidade: 80 G'
                     , detalhamento = 'Com sua textura suculenta e sabor inigualável, a linguiça é um verdadeiro deleite para os apreciadores de carne. Ela é cuidadosamente preparada a partir de cortes selecionados, resultando em uma mistura perfeita de carne e temperos. Sua versatilidade culinária permite que seja preparada de diversas maneiras, como grelhada, frita, assada, cozida ou até mesmo defumada.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='cerveja'
                     , nome = 'Cerveja'
                     , fornecedor = 'Cervejaria Nacional'
                     , preco =  13.10
                     , categoria = 'Bebidas'
                     , informacao = 'Quantidade: 600 ML'
                     , detalhamento = 'Se você é um verdadeiro apreciador de cervejas de qualidade, está prestes a vivenciar algo genuinamente especial. A Cerveja encanta desde o primeiro gole, com uma textura suculenta e um sabor que harmoniza perfeitamente no paladar. Cada aspecto é meticulosamente elaborado, desde a escolha dos ingredientes até o processo de fermentação, visando oferecer uma cerveja equilibrada e absolutamente deliciosa.'
                     , destaques = 'S' )
           , Produto ( id_produtos ='cha'
                     , nome = 'Chá Mate'
                     , fornecedor = 'Bebidas e Comércios LTDA'
                     , preco =  9.05
                     , categoria = 'Bebidas'
                     , informacao = 'Quantidade: 1.5 L'
                     , detalhamento = 'Se você é um amante de chá mate de qualidade, prepare-se para uma experiência verdadeiramente excepcional. Desde o primeiro gole, você será envolvido por uma textura suave e um sabor que é uma verdadeira sinfonia para o paladar. Cada detalhe é cuidadosamente considerado, desde a seleção das folhas até o processo de infusão, para garantir um chá mate equilibrado e absolutamente delicioso.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='coca'
                     , nome = 'Coca Cola'
                     , fornecedor = 'Casa do Refrigerante'
                     , preco =  10.00
                     , categoria = 'Bebidas'
                     , informacao = 'Quantidade: 2 L'
                     , detalhamento = 'Se você é um apreciador de bebidas refrescantes e saborosas, prepare-se para uma experiência única ao saborear a icônica Coca-Cola. Desde o primeiro gole, você será envolvido por uma explosão de sabor e uma sensação revigorante que desperta os sentidos. Cada detalhe da Coca-Cola é cuidadosamente elaborado, resultando em uma bebida equilibrada e irresistível. A combinação perfeita de ingredientes selecionados e a carbonatação ideal proporcionam um sabor inconfundível, que agrada a todos os paladares.'
                     , destaques = 'S' )                          
           , Produto ( id_produtos ='guarana'
                     , nome = 'Guaraná'
                     , fornecedor = 'Casa do Refrigerante'
                     , preco =  7.35
                     , categoria = 'Bebidas'
                     , informacao = 'Quantidade: 2 L'
                     , detalhamento = 'Se você é um amante de bebidas energéticas e revigorantes, prepare-se para descobrir o sabor autêntico e estimulante do Guaraná. Desde o primeiro gole, você será envolvido por uma experiência única e cheia de vitalidade. O Guaraná é uma bebida refrescante e característica da cultura brasileira. Com origem nas florestas tropicais da Amazônia, suas sementes contêm propriedades estimulantes e um sabor marcante. Cada detalhe é cuidadosamente pensado para garantir uma experiência equilibrada e revigorante.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='iorgute'
                     , nome = 'Iorgute de Morango'
                     , fornecedor = 'Fábrica de Laticínios'
                     , preco =  12.25
                     , categoria = 'Bebidas'
                     , informacao = 'Quantidade: 1.25 KG'
                     , detalhamento = 'Se você é fã de alimentos saudáveis e nutritivos, prepare-se para descobrir o delicioso mundo do iogurte. Desde a primeira colherada, você será cativado por sua textura cremosa e seu sabor refrescante, que traz uma verdadeira explosão de prazer para o paladar. Feito a partir do processo de fermentação do leite, ele é rico em probióticos, que auxiliam na saúde intestinal e fortalecem o sistema imunológico. Além disso, é uma excelente fonte de cálcio, proteínas e vitaminas essenciais.'
                     , destaques = 'S' )
           , Produto ( id_produtos ='leite'
                     , nome = 'Leite de Vaca'
                     , fornecedor = 'Fábrica de Laticínios'
                     , preco =  6.10
                     , categoria = 'Bebidas'
                     , informacao = 'Quantidade: 1 L'
                     , detalhamento = 'Uma das bebidas mais consumidas e nutritivas em todo o mundo, é uma verdadeira fonte de saúde e bem-estar. Desde o primeiro gole, você desfruta de um sabor suave e reconfortante que nos remete a momentos de infância e aconchego. É uma excelente fonte de cálcio, fundamental para a saúde óssea e dental, além de ser uma fonte de proteínas, vitaminas e minerais essenciais. Essa combinação nutricional torna o leite um aliado para o desenvolvimento e a manutenção de uma vida saudável.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='sucolaranja'
                     , nome = 'Suco de Laranja'
                     , fornecedor = 'Companhia do Suco'
                     , preco =  8.15
                     , categoria = 'Bebidas'
                     , informacao = 'Quantidade: 1 L'
                     , detalhamento = 'Uma das bebidas mais populares e refrescantes, é um verdadeiro tesouro da natureza. Cada gole oferece uma explosão de sabor cítrico e doce, transportando você para um momento de frescor e vitalidade. Feito a partir de laranjas frescas e suculentas, o suco de laranja é uma fonte natural de vitaminas, minerais e antioxidantes. É especialmente conhecido por seu alto teor de vitamina C, que fortalece o sistema imunológico, promove a saúde da pele e auxilia na absorção de outros nutrientes.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='sucouva'
                     , nome = 'Suco de Uva'
                     , fornecedor = 'Companhia do Suco'
                     , preco =  16.05
                     , categoria = 'Bebidas'
                     , informacao = 'Quantidade: 1.5 L'
                     , detalhamento = 'Uma verdadeira joia da natureza, oferece uma experiência sensorial única e um sabor marcante que agrada a todos os paladares. Cada gole desse suco puro e refrescante transporta você para os vinhedos ensolarados, onde as uvas são colhidas e transformadas em uma bebida suculenta e revitalizante. Feito a partir de uvas maduras e selecionadas, o suco de uva é rico em antioxidantes, vitaminas e minerais essenciais para a saúde. Essas propriedades naturais contribuem para fortalecer o sistema imunológico, promover a saúde cardiovascular e auxiliar na proteção celular.'
                     , destaques = 'N' )                        
           , Produto ( id_produtos ='acucar'
                     , nome = 'Açúcar'
                     , fornecedor = 'Fábrica Açucareira Doçura'
                     , preco =  4.05
                     , categoria = 'Complementos'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'Com sua textura fina e cristalina, ele se dissolve rapidamente, envolvendo seus alimentos e bebidas em uma doçura irresistível. Nossa marca se preocupa em oferecer um açúcar de alta qualidade, derivado de fontes vegetais selecionadas, garantindo sua pureza e sabor autêntico. Cada grãozinho do Açúcar Delícia é cuidadosamente produzido, seguindo padrões rigorosos de qualidade para atender às suas expectativas mais exigentes.'
                     , destaques = 'N' ) 
           , Produto ( id_produtos ='arroz'
                     , nome = 'Arroz'
                     , fornecedor = 'Fábrica Açucareira Doçura'
                     , preco =  4.30
                     , categoria = 'Complementos'
                     , informacao = 'Quantidade: 5 KG'
                     , detalhamento = 'Imagine um grão de arroz que combina nutrição, versatilidade e um sabor inigualável. Com sua coloração dourada e aroma delicioso, ele traz um toque especial para as suas refeições. O arroz é conhecido por sua riqueza em nutrientes essenciais. É uma excelente fonte de carboidratos complexos, que fornecem energia de forma sustentada ao longo do dia. Além disso, contém vitaminas e minerais como vitamina A, vitamina E e zinco que são importantes para a saúde ocular, imunidade e bem-estar geral.'
                     , destaques = 'S' )
           , Produto ( id_produtos ='azeite'
                     , nome = 'Azeite de Oliva'
                     , fornecedor = 'Supermecado Prático'
                     , preco =  25.85
                     , categoria = 'Complementos'
                     , informacao = 'Quantidade: 500 ML'
                     , detalhamento = 'Experimente a perfeição do azeite de oliva em cada gota. Com seu sabor delicado e aromas irresistíveis, ele eleva seus pratos a outro nível de excelência. Nosso azeite é produzido a partir de azeitonas cuidadosamente selecionadas e colhidas no momento ideal de maturação. Esse processo artesanal garante a máxima qualidade e preserva os benefícios nutricionais naturais. Além disso, é rico em ácidos graxos saudáveis e antioxidantes, proporcionando benefícios para o coração, a saúde celular e o sistema imunológico.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='cremeleite'
                     , nome = 'Creme de Leite'
                     , fornecedor = 'Supermecado Prático'
                     , preco =  4.59
                     , categoria = 'Complementos'
                     , informacao = 'Quantidade: 200 G'
                     , detalhamento = 'Nosso creme de leite é produzido com leite fresco e selecionado, cuidadosamente processado para garantir a máxima qualidade e cremosidade. Sua consistência perfeita é ideal para criar molhos aveludados, dar um toque especial a sopas, enriquecer sobremesas e adicionar um toque de indulgência às suas preparações favoritas. Além disso, é versátil em sua aplicação, oferecendo uma infinidade de possibilidades na culinária, seja na preparação de pratos salgados como massas, risotos, gratinados ou em sobremesas como mousses, tortas e cremes.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='macarrao'
                     , nome = 'Macarrão Parafuso'
                     , fornecedor = 'Casa das Massas'
                     , preco =  5.75
                     , categoria = 'Complementos'
                     , informacao = 'Quantidade: 500 G'
                     , detalhamento = 'Imagine a combinação perfeita de massa leve e textura irresistível. Nosso macarrão proporciona exatamente isso! Feito com ingredientes selecionados e cuidadosamente processado, ele é a base ideal para pratos deliciosos e satisfatórios. Nosso macarrão é produzido com trigo de alta qualidade, resultando em uma massa de consistência perfeita e sabor autêntico. Além disso, é de fácil preparo e rápido cozimento, perfeito para aqueles momentos em que você precisa de uma refeição prática e saborosa. Em poucos minutos, você terá uma refeição deliciosa na mesa.'
                     , destaques = 'S' )
           , Produto ( id_produtos ='mussarela'
                     , nome = 'Queijo Prato'
                     , fornecedor = 'Mercado Local'
                     , preco =  5.15
                     , categoria = 'Complementos'
                     , informacao = 'Quantidade: 400 G'
                     , detalhamento = 'Experimente a textura macia e o sabor delicado do queijo prato em cada mordida. Com sua consistência cremosa e sabor suave, ele é o complemento ideal para suas receitas e lanches favoritos. Nosso queijo prato é produzido com leite fresco e selecionado, seguindo rigorosos padrões de qualidade para garantir um produto de excelência. Sua textura derrete na boca, proporcionando uma experiência sensorial prazerosa em cada pedaço.'
                     , destaques = 'S' )
           , Produto ( id_produtos ='presunto'
                     , nome = 'Presunto'
                     , fornecedor = 'Mercado Local'
                     , preco =  2.10
                     , categoria = 'Complementos'
                     , informacao = 'Quantidade: 180 G'
                     , detalhamento = 'Nosso presunto é cuidadosamente selecionado e preparado com ingredientes de alta qualidade, resultando em uma carne macia e suculenta. Seu sabor defumado e característico adiciona um toque especial a qualquer prato, proporcionando uma experiência gastronômica excepcional. Além de seu sabor inigualável, é uma fonte de proteínas de alta qualidade, essenciais para uma alimentação saudável e equilibrada. Você pode saborear esse presunto com tranquilidade, sabendo que está adicionando valor nutricional ao seu cardápio.'
                     , destaques = 'N' ) 
           , Produto ( id_produtos ='sal'
                     , nome = 'Sal'
                     , fornecedor = 'Distribuidora de Sal'
                     , preco =  2.80
                     , categoria = 'Complementos'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'Descubra a pureza e a qualidade do sal em cada pitada. Com sua textura fina e cristalina, ele dissolve-se perfeitamente, realçando o sabor dos alimentos e trazendo equilíbrio às suas receitas. Nosso sal é produzido a partir de fontes naturais e selecionadas, passando por processos de purificação para garantir sua pureza e preservar seus minerais essenciais. Ele adiciona o toque final em seus pratos, proporcionando uma experiência gastronômica autêntica.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='abacate'
                     , nome = 'Abacate'
                     , fornecedor = 'Horta da Região'
                     , preco =  4.10
                     , categoria = 'Frutas'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'Descubra a suavidade e o sabor incrível do abacate a cada mordida. Com sua polpa cremosa e sabor único, ele é a escolha perfeita para adicionar um toque especial às suas refeições e lanches. Nosso abacate é cuidadosamente selecionado, garantindo a qualidade e o frescor que você merece. Rico em gorduras saudáveis, fibras e uma variedade de nutrientes, ele é uma escolha nutritiva para uma dieta equilibrada.'
                     , destaques = 'N' )                                                                  
           , Produto ( id_produtos ='banana'
                     , nome = 'Banana Prata'
                     , fornecedor = 'Horta da Região'
                     , preco =  8.99
                     , categoria = 'Frutas'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'Nossas bananas são cuidadosamente selecionadas, garantindo a qualidade e o frescor que você merece. Além de ser uma opção deliciosa, a Banana Delícia é uma fonte de nutrientes essenciais, como potássio, vitamina C e fibras alimentares. Além de seu sabor irresistível, ela oferece benefícios para a saúde. O potássio ajuda a regular a pressão arterial e a função muscular, enquanto a vitamina C fortalece o sistema imunológico e as fibras alimentares auxiliam na digestão saudável.'
                     , destaques = 'S' )  
           , Produto ( id_produtos ='goiaba'
                     , nome = 'Goiaba'
                     , fornecedor = 'Mercado Mineiro'
                     , preco =  7.60
                     , categoria = 'Frutas'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'Nossas goiabas são cuidadosamente selecionadas, garantindo a qualidade e o frescor que você merece. Além de ser uma opção deliciosa, a Goiaba Delícia é uma excelente fonte de vitamina C, fibras e antioxidantes. Além de seu sabor incrível, a Goiaba Delícia oferece benefícios para a saúde. A vitamina C fortalece o sistema imunológico, as fibras alimentares auxiliam na digestão saudável e os antioxidantes ajudam a combater os radicais livres no organismo.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='maca'
                     , nome = 'Maça Fuji'
                     , fornecedor = 'Mercado Mineiro'
                     , preco =  5.98
                     , categoria = 'Frutas'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'Nossas maçãs são cuidadosamente selecionadas, garantindo a qualidade e o frescor que você merece. Além de ser uma opção refrescante, ela é rica em fibras, vitaminas e antioxidantes que contribuem para uma alimentação equilibrada. As fibras alimentares auxiliam na digestão saudável, as vitaminas fortalecem o sistema imunológico e os antioxidantes ajudam a combater os radicais livres no organismo, tornando-a ainda mais atrativa e saudável para as suas refeições.'
                     , destaques = 'S' )
           , Produto ( id_produtos ='mamao'
                     , nome = 'Mamão Papaya'
                     , fornecedor = 'Horta Profissional'
                     , preco =  14.50
                     , categoria = 'Frutas'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'O mamão papaya é uma variedade especial de mamão, conhecido por sua polpa alaranjada, doçura intensa e textura macia. Cada mordida é uma explosão de sabor tropical, transportando você para um paraíso frutado. Nossos mamões são cultivados com cuidado e colhidos no momento perfeito de maturação, garantindo que você desfrute de um mamão de qualidade superior. Sua polpa suculenta e aroma delicioso tornam cada fatia uma experiência sensorial inigualável.'
                     , destaques = 'S' )
           , Produto ( id_produtos ='manga'
                     , nome = 'Manga Tommy'
                     , fornecedor = 'Horta Profissional'
                     , preco =  5.39
                     , categoria = 'Frutas'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'A manga é uma fruta exótica e irresistivelmente suculenta, conhecida por sua polpa macia, doçura intensa e aroma tropical. Cada mordida é uma explosão de sabores que transporta você para um paraíso frutado. Nossas mangas são cultivadas com esmero e colhidas no momento perfeito de maturação, garantindo que você desfrute de uma manga de alta qualidade. Sua polpa dourada e suculenta derrete na boca, proporcionando uma experiência sensorial única.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='pera'
                     , nome = 'Pêra'
                     , fornecedor = 'Horta Natural'
                     , preco =  4.00
                     , categoria = 'Frutas'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'Nossas pêras são cuidadosamente selecionadas, garantindo qualidade e frescor excepcionais. Colhidas no momento ideal de maturação, elas são a expressão máxima da natureza, prontas para serem apreciadas em sua melhor forma. Além do sabor incrível, ela oferece benefícios para a saúde uma vez que é rica em fibras, vitaminas e antioxidantes, auxiliando na digestão saudável, fortalecendo o sistema imunológico e contribuindo para uma dieta equilibrada.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='uva'
                     , nome = 'Uva'
                     , fornecedor = 'Horta Natural'
                     , preco =  13.50
                     , categoria = 'Frutas'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'Imagine uma uva que é cultivada com todo o cuidado e carinho em vinícolas seletas, onde cada videira recebe atenção individualizada para garantir sua qualidade excepcional. As uvas são colhidas no ponto perfeito de maturação, quando sua doçura está no auge e suas propriedades nutricionais são amplamente preservadas. Com um visual deslumbrante e suculência irresistível, ela agrada aos olhos e ao paladar. Cada mordida é uma explosão de sabores: a doçura natural equilibrada com uma acidez suave, criando uma harmonia perfeita.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='beterraba'
                     , nome = 'Beterraba'
                     , fornecedor = 'Central Hortifruti'
                     , preco =  3.89
                     , categoria = 'Verduras'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'Se você está em busca de uma opção saudável e versátil para incluir em sua dieta, apresentamos a você a maravilhosa beterraba. Essa raiz vibrante e de sabor único é um tesouro nutritivo que pode revolucionar seus pratos e elevar sua saúde a um novo nível. Com sua cor intensa e sabor adocicado, ela é um verdadeiro presente da natureza. Originária do Mediterrâneo, ela tem sido apreciada há séculos tanto por seu valor culinário quanto por seus benefícios para a saúde. Suas folhas também podem ser consumidas, oferecendo uma variedade de nutrientes adicionais.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='brocolis'
                     , nome = 'Brócolis'
                     , fornecedor = 'Central Hortifruti'
                     , preco =  14.50
                     , categoria = 'Verduras'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'Se você está em busca de um alimento que seja ao mesmo tempo saudável e delicioso, apresentamos a você o incrível brócolis. Com sua aparência única e sabor característico, essa verdura verde vibrante é um verdadeiro tesouro nutricional que pode transformar sua alimentação e impulsionar sua saúde. Originário da região do Mediterrâneo, o brócolis tem conquistado o paladar de pessoas em todo o mundo devido à sua combinação única de sabor e valor nutritivo. Rico em fibras, vitaminas e minerais essenciais, ele é um verdadeiro superalimento que merece um lugar especial em sua dieta.'
                     , destaques = 'S' )
           , Produto ( id_produtos ='cebola'
                     , nome = 'Cebola'
                     , fornecedor = 'Mercado da Cidade'
                     , preco =  2.50
                     , categoria = 'Verduras'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'Quando se trata de aromas irresistíveis e sabores complexos, a cebola certamente ocupa um lugar de destaque na culinária. Essa hortaliça versátil e amplamente utilizada é muito mais do que um simples ingrediente, é uma verdadeira protagonista que adiciona profundidade e caráter aos pratos ao redor do mundo. Originária da Ásia Central, a cebola tem uma longa história como um alimento básico nas cozinhas de diferentes culturas. Seu sabor inconfundível e sua capacidade de aprimorar o sabor de outros ingredientes fazem dela um componente essencial em inúmeras receitas, desde pratos caseiros até criações gastronômicas requintadas.'
                     , destaques = 'N' ) 
           , Produto ( id_produtos ='cenoura'
                     , nome = 'Cenoura'
                     , fornecedor = 'Mercado da Cidade'
                     , preco =  2.50
                     , categoria = 'Verduras'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'Se você procura um alimento versátil, repleto de benefícios para a saúde e com um sabor delicioso, apresentamos a você a maravilhosa cenoura. Com sua cor vibrante, textura crocante e sabor levemente adocicado, essa raiz nutritiva é uma estrela na culinária e um tesouro para a sua saúde. Originária da região do Mediterrâneo, a cenoura é um dos vegetais mais populares e amplamente consumidos em todo o mundo. Ela é uma excelente fonte de nutrientes essenciais, incluindo vitamina A, vitamina C, vitamina K, potássio e fibras. Essa combinação poderosa traz uma série de benefícios para o organismo.'
                     , destaques = 'S' )
           , Produto ( id_produtos ='couveflor'
                     , nome = 'Couve Flor'
                     , fornecedor = 'Hortifruti'
                     , preco =  7.85
                     , categoria = 'Verduras'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'Com sua aparência única e sabor suave, essa flor comestível é um tesouro nutricional que pode transformar suas refeições e trazer uma infinidade de benefícios para a sua saúde. A couve-flor pertence à família das crucíferas, que inclui vegetais como brócolis, repolho e couve-de-bruxelas. Essa flor impressionante é rica em nutrientes essenciais e oferece uma variedade de benefícios para o organismo.'
                     , destaques = 'N' )                                                                                                                                                                                                         
           , Produto ( id_produtos ='couve'
                     , nome = 'Couve'
                     , fornecedor = 'Hortifruti'
                     , preco =  6.59
                     , categoria = 'Verduras'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'A couve, pertencente à família das crucíferas, é um vegetal versátil e amplamente apreciado em todo o mundo. Além de ser um ingrediente popular em saladas, ela pode ser cozida, refogada, utilizada em sucos verdes, sopas e muito mais. Sua versatilidade permite que você a incorpore em uma ampla variedade de pratos, proporcionando um toque de frescor e sabor. Ela é uma excelente fonte de vitaminas, minerais e antioxidantes, tornando-se uma escolha nutritiva para fortalecer o seu corpo. A couve é rica em vitamina K, vitamina C, vitamina A, além de conter folato, cálcio e potássio.'
                     , destaques = 'N' )
           , Produto ( id_produtos ='pepino'
                     , nome = 'Pepino Japonês'
                     , fornecedor = 'Mercado da Cidade'
                     , preco =  5.80
                     , categoria = 'Verduras'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'Com sua textura crocante, sabor suave e propriedades hidratantes, esse pepino é um verdadeiro deleite para o paladar e um aliado para o bem-estar. O pepino japonês, também conhecido como pepino kyuri, é uma variedade especial de pepino originária do Japão. Composto por cerca de 95% de água, o pepino é um excelente aliado para manter o corpo hidratado, sendo assim uma opção refrescante e saudável para matar a sede e fornecer um alívio instantâneo.'
                     , destaques = 'S' )
           , Produto ( id_produtos ='tomate'
                     , nome = 'Tomate'
                     , fornecedor = 'Hortifruti'
                     , preco =  11.70
                     , categoria = 'Verduras'
                     , informacao = 'Quantidade: 1 KG'
                     , detalhamento = 'Originário da América do Sul, o tomate ganhou destaque e se tornou um ingrediente fundamental em pratos que vão desde saladas refrescantes até molhos de tomate ricos e ensopados reconfortantes. O sabor característico do tomate, que combina acidez e doçura, é uma verdadeira explosão de sabor em cada mordida. Além disso, é uma excelente fonte de vitaminas, minerais e antioxidantes.'
                     , destaques = 'S' )                                                          
]